### PR TITLE
New coroutine support

### PR DESCRIPTION
**Pull request by ialex32x**
directly use a lua function (lua coroutine function) in the
MonoBehaviour.StartCoroutine method like a csharp native coroutine.

example:
my_behaviour:StartCoroutine(function ()
    coroutine.yield(WaitForSeconds(5))
    coroutine.yield(MyCSharpClass.MyCustomCSharpMethod(function ()
       print("there")
    end))
    print("here")
    --  MyCSharpClass.MyCustomCSharpMethod  returns IEnumerator
end)

csharp:
[CustomLuaClass]
public class MyCSharpClass {
  public static IEnumerator MyCustomCSharpMethod(LuaFunction func)
  {
      yield return new WaitForSeconds(5f);
     func.call();
  }
}

### CODE REVIEW

**Comment by pangweiwei** [comment]
This feature is very cool, but I think this is not complete, you can repeatedly run your example, after many times it will crash or not respond.

**Comment by ialex32x** [comment]
ok, I'll fix it ASAP.

**Comment by ialex32x** [comment]
I can't reproduce the problem. Is there any difference between our environment? 
Unity 5.5.0f3, OSX. Selected platform is PC,Mac&Linux Standalone.

**Comment by ialex32x** [comment]
I'll try it again on Windows.

**Comment by pangweiwei** [comment]
I also work on Unity5.5, OSX.

在 2017-01-25 10:21:47，"huliangjie" <notifications@github.com> 写道：


I can't reproduce the problem. Is there any difference between our environment?
Unity 5.5.0f3, OSX. Selected platform is PC,Mac&Linux Standalone.

**Comment by pangweiwei** [comment]
I find reproduced method, modify new_coroutine.txt to:

`function main()
	return function (obj)
		if NewCoroutine.MyMethod == nil then 
			print("please export the class to lua at first.")
			return 
		end
		print("lua got object", obj)
		obj:StartCoroutine(function ()
			return 1,2,3
		end)
		print("code after StartCoroutine")
	end
end`

1) add linebreak at:LuaThreadWrapper.cs:64
2) add linebreak at:LuaThreadWrapper.cs:89
3) start debug in mono editor

repeatedly run game and stop game will cause ANR

**Comment by pangweiwei** [comment]
I find reproduced method, modify new_coroutine.txt to:

function main()
return function (obj)
if NewCoroutine.MyMethod == nil then
print("please export the class to lua at first.")
return
end
print("lua got object", obj)
obj:StartCoroutine(function ()
return 1,2,3
end)
print("code after StartCoroutine")
end
end

add linebreak at:LuaThreadWrapper.cs:64
add linebreak at:LuaThreadWrapper.cs:89
start debug in mono editor
repeatedly run game and stop game will cause editor ANR

but, I don't think that's your problem, maybe slua or mono-debugger's fault.
I will dig deep.

**Comment by pangweiwei** [comment]
I think you should process return value from return statement, like return 1,2,3 rather than yield( 1,2,3 )

**Pull request closed without merging**
