### PR TITLE
Improve speed of binding, reduce gc-alloc on start 

### PR DESCRIPTION
**Pull request by chiuan**
- mod:加速初始化Bind效率提高20~30%,并且减少GC
- add:Timer增加DeleteAll接口

### CODE REVIEW

**Comment by pangweiwei** [comment]
This branch has conflicts that must be resolved

**Comment by chiuan** [comment]
what confilcts now?

**Comment by pangweiwei** [comment]
Auto-merging Assets/Slua/Script/LuaSvr.cs
CONFLICT (content): Merge conflict in Assets/Slua/Script/LuaSvr.cs
Auto-merging Assets/Slua/Editor/LuaCodeGen.cs
CONFLICT (content): Merge conflict in Assets/Slua/Editor/LuaCodeGen.cs
Auto-merging Assets/Slua/Editor/CustomExport.cs
CONFLICT (content): Merge conflict in Assets/Slua/Editor/CustomExport.cs
Automatic merge failed; fix conflicts and then commit the result.

**Comment by chiuan** [comment]
@pangweiwei  use the best way to bind when running.. no reflection anymore..

**Comment by pangweiwei** [comment]
你的这个修改，到只main demo报告错误：
[string "..."]:4: No matched override function to call
stack traceback:
	[C]: in function 'assert'
	[string "..."]:4: in function <[string "..."]:3>
	(tail call): ?
	main:24: in function <main:18>
UnityEngine.Debug:LogError(Object)
SLua.LuaState:errorReport(IntPtr) (at Assets/Plugins/Slua_Managed/LuaState.cs:676)
LuaInterface.LuaDLL:lua_pcall(IntPtr, Int32, Int32, Int32)
SLua.LuaFunction:pcall(Int32, Int32) (at Assets/Plugins/Slua_Managed/LuaState.cs:206)
SLua.LuaFunction:innerCall(Int32, Int32) (at Assets/Plugins/Slua_Managed/LuaState.cs:216)
SLua.LuaFunction:call() (at Assets/Plugins/Slua_Managed/LuaState.cs:225)
SLua.LuaSvr:start(String) (at Assets/Plugins/Slua_Managed/LuaSvr.cs:188)
Main:complete() (at Assets/Slua/example/Main.cs:39)
SLua.<init>c__AnonStorey3:<>m__17() (at Assets/Plugins/Slua_Managed/LuaSvr.cs:157)
SLua.<waitForDebugConnection>c__Iterator1:MoveNext() (at Assets/Plugins/Slua_Managed/LuaSvr.cs:62)

**Comment by chiuan** [comment]
@pangweiwei 没有问题啊？ 你应该没合对吧

**Comment by chiuan** [comment]
是有问题。我再看下。有些没有有些有。奇怪了

**Comment by chiuan** [comment]
@pangweiwei  if Custom Bind first will lost "parent" ??

**Comment by chiuan** [comment]
@pangweiwei  i have fix. i changed matchType of char[] and byte[] for my project usage. but this will cause the String.Split(char[]) error.

**Comment by chiuan** [comment]
先不要合。我把id优化和静态方法绑定去_s结尾一块做了先。

**Comment by pangweiwei** [comment]
哥，就等你的pr了，就可以beta4了，然后就可以release了

**Comment by chiuan** [comment]
@pangweiwei 最近忙啊。。天天11点。。完整的full speedup估计得过完这1-2星期。。。

**Comment by pangweiwei** [comment]
你在那家没有人性的公司啊？

**Comment by wlgys8** [comment]
太可怕

**Pull request closed without merging**
